default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: events_development

test:
  <<: *default
  database: events_test

production:
  <<: *default
  database: events_production
  username: <%= ENV["TEST_APP_DATABASE_USER"] %> # Set your Heroku database username here
  password: <%= ENV["TEST_APP_DATABASE_PASSWORD"] %> # Set your Heroku database password here
